# Generated by Django 3.1.1 on 2020-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201020_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
