# Generated by Django 3.1.1 on 2020-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201020_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/no_image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
